# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ReactJS

on:
  push:
    branches:
      - master
    paths: 
      - "ClientApp/**"
  pull_request:
    branches:
      - master
    paths: 
      - "ClientApp/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: cd ClientApp && npm install
    - name: Build App
      run: cd ClientApp && npm run build
    # - name: Test
    #   run: cd ClientApp && npm run test
