name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: windows-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        shell: bash
        run: |
          # Build everything
          dotnet publish -c Release -o "$release_name"
          
          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
         
          # Delete output directory
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "LMIS*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
